In [1]:
import pandas as pd
club = pd.read_csv('lending-club-datac.csv', low_memory=False)

In [2]:
club.columns

Index(['term', 'grade', 'sub_grade', 'home_ownership', 'purpose', 'dti',
       'revol_util', 'total_rec_late_fee', 'bad_loans', 'bad_loans_1',
       'emp_length_num', 'short_emp', 'last_delinq_none',
       'last_major_derog_none'],
      dtype='object')

In [3]:
club.shape

(46300, 14)

In [4]:
y = club['bad_loans_1']
x = club[['term','grade','sub_grade','home_ownership','purpose','dti','revol_util','total_rec_late_fee','emp_length_num','short_emp','last_delinq_none','last_major_derog_none'
]]

from sklearn.cross_validation import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2,random_state=4)

In [5]:
x_train.shape

(37040, 12)

In [6]:
#from sklearn.preprocessing import OneHotEncoder
#enc = OneHotEncoder()
#x_train = enc.fit(x_train)
#x_test = enc.fit(x_test)

In [7]:
from sklearn.tree import DecisionTreeClassifier
small_model = DecisionTreeClassifier(criterion="entropy",random_state=1,max_depth=2)
decision_tree_model = DecisionTreeClassifier(criterion="entropy",random_state=1)

In [8]:
small_model = small_model.fit(x_train,y_train)
decision_tree_model = decision_tree_model.fit(x_train,y_train)

In [9]:
decision_tree_model.predict([[1,1,7,0,3,18.65,42.4,0,6,0,1,1],[0,1,6,0,9,3.39,31.4,0,5,0,1,1
],[1,2,13,1,0,1,9.4,0,1,1,1,1
],[1,5,26,2,9,5.55,32.6,0,5,0,1,1
]])

array([-1,  1, -1, -1], dtype=int64)

In [10]:
decision_tree_model.predict_proba(x_test)[0:10,]

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.]])

In [11]:
import numpy
numpy.mean(decision_tree_model.predict_proba(x_test)[:,1])

0.50431965442764581

In [12]:
numpy.max(decision_tree_model.predict_proba(x_test)[:,1])

1.0

In [13]:
small_model.predict_proba([[1,1,7,0,3,18.65,42.4,0,6,0,1,1],[0,1,6,0,9,3.39,31.4,0,5,0,1,1
],[1,2,13,1,0,1,9.4,0,1,1,1,1
],[1,5,26,2,9,5.55,32.6,0,5,0,1,1
]])

array([[ 0.53392961,  0.46607039],
       [ 0.29731811,  0.70268189],
       [ 0.53392961,  0.46607039],
       [ 0.53392961,  0.46607039]])

In [14]:
decision_tree_model.predict_proba([[1,1,7,0,3,18.65,42.4,0,6,0,1,1],[0,1,6,0,9,3.39,31.4,0,5,0,1,1
],[1,2,13,1,0,1,9.4,0,1,1,1,1
],[1,5,26,2,9,5.55,32.6,0,5,0,1,1
]])

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [15]:
from sklearn import metrics
small_model_pred = small_model.predict(x_test)
print(metrics.accuracy_score(y_test,small_model_pred))

0.58120950324


In [16]:
dtc_pred = decision_tree_model.predict(x_test)
print(metrics.accuracy_score(y_test,dtc_pred))

0.571706263499


In [17]:
small_model_pred = small_model.predict(x_train)
print(metrics.accuracy_score(y_train,small_model_pred))

0.586906047516


In [18]:
dtc_pred = decision_tree_model.predict(x_train)
print(metrics.accuracy_score(y_train,dtc_pred))

1.0


In [19]:
big_model = DecisionTreeClassifier(criterion="entropy",random_state=1,max_depth=10)
big_model = big_model.fit(x_train,y_train)

In [20]:
big_model_pred = big_model.predict(x_train)
print(metrics.accuracy_score(y_train,big_model_pred))

0.667440604752


In [21]:
big_model_pred = big_model.predict(x_test)
print(metrics.accuracy_score(y_test,big_model_pred))

0.631425485961


In [22]:
y_test.shape

(9260,)

In [23]:
dtc_pred = decision_tree_model.predict(x_test)
print(metrics.accuracy_score(y_test,dtc_pred))

0.571706263499


In [24]:
print(metrics.confusion_matrix(y_test,dtc_pred))

[[2597 1973]
 [1993 2697]]
